libpthread_linux_arch_CSRC = pthread_once.c lowlevellock.c
libc_linux_arch_CSRC = fork.c

CFLAGS-pthread_once.c = -DNOT_IN_libc -DIS_IN_libpthread
CFLAGS-lowlevellock.c = -DNOT_IN_libc -DIS_IN_libpthread

ifeq ($(UCLIBC_HAS_STDIO_FUTEXES),y)
CFLAGS-fork.c = -D__USE_STDIO_FUTEXES__
endif
CFLAGS-OMIT-fork.c = -DNOT_IN_libc -DIS_IN_libpthread

