/* vi: set sw=4 ts=4: */
/* csky  ELF shared library loader suppport
 *
 * Copyright (C) 2010 - 2010 Yunhai Shang(yunhai_shang@c-sky.com)
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. The name of the above contributors may not be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

static const char *_dl_reltypes_tab[] = {
	[0]"R_CKCORE_NONE","R_CKCORE_ADDR32","R_CKCORE_PCRELIMM8BY4","R_CKCORE_PCRELIMM11BY2",
	[4]"R_CKCORE_PCRELIMM4BY2","R_CKCORE_PCREL32","R_CKCORE_PCRELJSR_IMM11BY2","R_CKCORE_GNU_VTINHERIT",
	[8]"R_CKCORE_GNU_VTENTRY","R_CKCORE_RELATIVE","R_CKCORE_COPY","R_CKCORE_GLOB_DAT",
	[12]"R_CKCORE_JUMP_SLOT","R_CKCORE_GOTOFF","R_CKCORE_GOTPC","R_CKCORE_GOT32",
	[16]"R_CKCORE_PLT32","R_CKCORE_ADDRGOT","R_CKCORE_ADDRPLT","R_CKCORE_PCREL_IMM26BY2",
    [20]"R_CKCORE_PCREL_IMM16BY2","R_CKCORE_PCREL_IMM16BY4","R_CKCORE_PCREL_IMM10BY2","R_CKCORE_PCREL_IMM10BY4",
    [24]"R_CKCORE_ADDR_HI16","R_CKCORE_ADDR_LO16","R_CKCORE_GOTPC_HI16","R_CKCORE_GOTPC_LO16",
    [28]"R_CKCORE_GOTOFF_HI16","R_CKCORE_GOTOFF_LO16","R_CKCORE_GOT12","R_CKCORE_GOT_HI16",
    [32]"R_CKCORE_GOT_LO16","R_CKCORE_PLT12","R_CKCORE_PLT_HI16","R_CKCORE_PLT_LO16",
    [36]"R_CKCORE_ADDRGOT_HI16","R_CKCORE_ADDRGOT_LO16","R_CKCORE_ADDRPLT_HI16","R_CKCORE_ADDRPLT_LO16",
    [40]"R_CKCORE_PCREL_JSR_IMM26BY2","R_CKCORE_TOFFSET_LO16","R_CKCORE_DOFFSET_LO16", "R_CKCORE_PCREL_IMM18BY2",
    [44]"R_CKCORE_DOFFSET_IMM18", "R_CKCORE_DOFFSET_IMM18BY2", "R_CKCORE_DOFFSET_IMM18BY4", "R_CKCORE_GOTOFF_IMM18",
    [48]"R_CKCORE_GOT_IMM18BY4", "R_CKCORE_PLT_IMM18BY4", "R_CKCORE_PCREL_IMM7BY4", "R_CKCORE_TLS_LE32", 
    [52]"R_CKCORE_TLS_IE32", "R_CKCORE_TLS_GD32", "R_CKCORE_TLS_LDM32", "R_CKCORE_TLS_LDO32", 
    [56]"R_CKCORE_TLS_DTPMOD32" ,"R_CKCORE_TLS_DTPOFF32"
};

